# Generated by Django 5.0.7 on 2024-07-10 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_photo',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='static/srcs/creepy-cat.webp', upload_to='profile_pics', verbose_name='Photo de profil'),
        ),
    ]