# Generated by Django 5.0.7 on 2024-07-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_user_profile_photo_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='creepy-cat.webp', upload_to='imgs/profils/'),
        ),
    ]
