# Generated by Django 5.0.7 on 2024-07-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pong_games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='pong_max_exchange',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='pong_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='pong_winrate',
            field=models.IntegerField(default=0),
        ),
    ]
