version: '3'

networks:
  Transcendence:
    driver: bridge

services:
  postgres:
    image: postgres
    container_name: postgres
    networks:
      - Transcendence
    environment:
      - POSTGRES_USER=bonjour
      - POSTGRES_PASSWORD=password
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - app:/usr/share/nginx/html
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=ajakubcz.42.fr
      - NGINX_PORT=80
    # depends_on:
    #   - django

  # django:
  #   image: django
  #   container_name: django
  #   volumes:
  #     - back:/var/www/wordpress
  #   networks:
  #     - Transcendence
  #   # depends_on:
  #   #   - postgreSQL
  #   # restart: on-failure
  #   expose: 
  #     - "9000"



volumes:
  app:
    driver: local # ici nous stockons le volume en local
    driver_opts:
      type: 'none' # aucun type spécifique
      o: 'bind'
      device: './app' #Ou stocker le dossier sur votre ordinateur en local

  back:
    driver: local # ici nous stockons le volume en local
    driver_opts:
      type: 'none' # aucun type spécifique
      o: 'bind'
      device: './back' #Ou stocker le dossier sur votre ordinateur en local
  db:
    driver: local
    driver_opts:
      type: 'none' 
      o: 'bind' # Les Bind Mounts sont des volumes qui se montent sur un chemin d'accès à l'hôte, et ils peuvent être modifiés par d'autres processus en dehors de docker.
      device: './db' #Ou stocker le dossier sur votre ordinateur en local