networks:
  Transcendence:
    driver: bridge

services:
  postgres:
    image: postgres
    container_name: postgres
    networks:
      - Transcendence
    env_file: .env
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    expose:
      - "5432"

  nginx:
    container_name: nginx
    networks:
      - Transcendence
    build:
      context: docker
      dockerfile: Dockerfile-nginx 
    volumes:
      - nginx-static:/transcendence/static/
      - nginx-media:/transcendence/media/
    ports:
      - "8042:443"
    env_file: .env
    depends_on:
      - django

  django:
    container_name: django
    networks:
      - Transcendence
    env_file: .env
    build:
      context: docker
      dockerfile: Dockerfile-django
    volumes:
      - back:/transcendence
    depends_on:
      - postgres
    expose:
      - "8000"
    restart: always



volumes:
  nginx-static:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './back/app/static'
  
  nginx-media:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './back/media'

  back:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './back'
  db:
    driver: local