networks:
  Transcendence:
    driver: bridge

services:
  postgres:
    image: postgres
    container_name: postgres
    networks:
      - Transcendence
    # build:
    #   context: docker # ou se trouve son Dockerfile
    #   dockerfile: Dockerfile-postgres # le nom du Dockerfile ?!
    env_file: .env
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    expose:
      - "5432"

  nginx:
    # image: nginx
    container_name: nginx
    networks:
      - Transcendence
    build:
      context: docker # ou se trouve son Dockerfile
      dockerfile: Dockerfile-nginx # le nom du Dockerfile ?!
    volumes:
      - nginx:/transcendence/static/
    ports:
      - "8042:443"
    env_file: .env
    depends_on:
      - django

  django:
    # image: django
    container_name: django
    networks:
      - Transcendence
    env_file: .env
    build:
      context: docker # ou se trouve son Dockerfile
      dockerfile: Dockerfile-django # le nom du Dockerfile ?!
    volumes:
      - back:/transcendence
    depends_on:
      - postgres
    expose:
      - "8000"
    restart: always



volumes:
  nginx:
    driver: local # ici nous stockons le volume en local
    driver_opts:
      type: 'none' # aucun type spécifique
      o: 'bind'
      device: './back/app/static' #Ou stocker le dossier sur votre ordinateur en local

  back:
    driver: local # ici nous stockons le volume en local
    driver_opts:
      type: 'none' # aucun type spécifique
      o: 'bind'
      device: './back' #Ou stocker le dossier sur votre ordinateur en local
  db:
    driver: local
    # driver_opts:
    #   type: 'none' 
    #   o: 'bind' # Les Bind Mounts sont des volumes qui se montent sur un chemin d'accès à l'hôte, et ils peuvent être modifiés par d'autres processus en dehors de docker.
    #   device: './db' #Ou stocker le dossier sur votre ordinateur en local