FROM python

RUN python -m pip install Django
RUN apt-get update \
    && apt-get install -y netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*
RUN mkdir transcendence
RUN pip install psycopg
RUN pip install psycopg2
RUN pip install Pillow
# install channels for use websocket
RUN pip install channels
RUN pip install daphne
RUN pip install torch --index-url https://download.pytorch.org/whl/cpu
RUN pip install numpy
RUN pip install matplotlib
RUN pip install djangorestframework
COPY django-setup.sh /
RUN chmod +x django-setup.sh
RUN pip install web3
RUN pip install --upgrade parsimonious
CMD ./django-setup.sh