FROM python

RUN python -m pip install Django
RUN apt-get update \
    && apt-get install -y netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*
RUN mkdir app
RUN pip install psycopg2
RUN pip install Pillow
COPY django-setup-dev.sh /
RUN chmod +x django-setup-dev.sh
CMD ./django-setup-dev.sh