FROM python

RUN python -m pip install Django
RUN apt-get update \
    && apt-get install -y netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*
RUN mkdir app
RUN pip install psycopg2
COPY django-setup.sh /
RUN chmod +x django-setup.sh
CMD ./django-setup.sh