FROM python

RUN python -m pip install Django
RUN apt-get update \
    && apt-get install -y netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*
RUN mkdir transcendence
RUN pip install psycopg
RUN pip install psycopg2
RUN pip install Pillow
# install channels for use websocket
RUN pip install channels
RUN pip install daphne
COPY django-setup-dev.sh /
RUN chmod +x django-setup-dev.sh
CMD ./django-setup-dev.sh