# Generated by Django 5.0.6 on 2024-05-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertest',
            name='user_id',
            field=models.IntegerField(default=404),
        ),
    ]
