# Generated by Django 5.0.6 on 2024-05-23 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0002_usertest_user_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userTest',
            new_name='Member',
        ),
    ]
